### ISSUE TITLE
Constitution Critique, T.L. Hulsey

### ISSUE THREAD

**Issue by hulsey88** [luisrayas3/golden-liberty#1]
I; Rights of all persons:
>>“inherent natural rights”: Does that mean the rights enumerated in the first eight Amendments to the U.S. Constitution? Or does it mean substantive rights?

>>Is a religious belief that mandates the killing of unbelievers to be treated “with dignity and respect”? Is contempt for short people to be prosecuted under the law?

>>Does self ownership forbid incarceration for any crime?

>>Does the “equal natural right to move about the earth” mean that no jurisdictional borders shall exist?

>>What agency will enforce remuneration for these “transgressions”?

I; Rights of the accused:
>>Is the more restrictive “beyond a reasonable doubt” standard now to apply to torts as well?

>>If the “sanction” does not “surpass the degree of the original transgression,” then crime becomes a winning proposition: Getting caught would mean no more than restoring what was taken or damaged.

II; Right to secession:
>>If the seceding city views some obligation as an exit tax, is the League permitted to use violence against it?

II; Republican and transparent government:
Cities shall recognize the popular sovereignty of each of its Citizens. 
>>This is not clear, since “popular” and “each” refer to a group and to an individual, respectively.

>>“Equal opportunity for suffrage” could mean penalizing those who don’t vote, among other things.

All bodies [...] shall be subject to audit by the Ministry of Accountability. 
>>This “Ministry of Accountability” is thus given veto power over every aspect of government.

II; Courts:
>>You advocate compulsory jury duty.

II; Militias:
>>“Material defense” should be clearly distinguished from “defense.”

II; Legislative powers:
>>What authority will enforce this legal standardization among the cities?

>>This paragraph seems to authorize cities to suppress disturbance of the peace, but is not clear.

>>“Natural authority” should be clearly distinguished from “authority.”

II; Collection of natural rent:
>>The “ground rent” issue lets loose an avalanche of other issues: Are landlords to have their rents confiscated without compensation? Is ground rent to be the sole tax? How is it to be distributed?

>>Does “willing to pay its rent” allow rent charges as high as the “exclusive” users care to charge? If so, the purpose of ground rent is defeated; if not, then the users’ property is being taken.

II; Power to spend:
>>This paragraph seems to distinguish between ground rent equally distributed among citizens and ground rent withheld for “public” use, with no restriction on the size of the “public” share.

>>If not set (redundantly) by the existing market, then what is the “appropriate rent” according to the ground rent scheme?

II; Establishment of money:
>>If a city distributes the money of its choosing for the dividend, it may be CBDC, “social credits,” or any arbitrary medium.

II; Harboring fugitives:
>>Must a city deliver up a person accused of an act that is not a legal offense under its own laws?

IV; Councils of the League:
>>The distinction between League and City seems similar to that of Federal and State, but this is not spelled out.

IV; Representation in the Council of Citizens:
>>What is the advantage of vote delegation?

>>What is the purpose of Council of Citizen forums?

IV; Election of the Council of Cities:
>>“Consistent with the principles of republicanism” could mean almost anything.

IV; Plurality votes:
>>Why not just say 28%, 40%, and 46% plurality? These calculations serve only to confuse.

IV; Directives:
>>Nowhere are “directive” and “ministry” spelled out (not even in section VI), despite the elaborate business of their pluralities.

IV; Rules, processes, and schedule:
>>Nowhere is “council” spelled out, despite the elaborate business of its pluralities.

V; Office of the President:
>>Does “unarmed” mean “bureaucrats”?

>>Is the national army a collection of militias coordinated by protocols? If not, what is the nature of the national army?

The President shall serve in their office until they choose to abdicate[...].
>>This seems to be a “President-for-Life and Lord of all the Beasts of the Earth and Fishes of the Sea” position, like that of Idi Amin.

VI; Naturalization of Cities and Citizens:
>>I’m not sure of the value of passports when no borders exist (see above).

VI; Citizen's dividend:
>>There seems to be no restriction on the amount that the Councils can “allocate” to themselves for some “public” use.

VI; Ministry of Accountability:
>>The “Ministry of Accountability” seems to have veto power over the entire government.

**Comment by luisrayas3** [comment]
T.L., thanks very much for your thorough critique, it is genuinely appreciated. I've addressed your comments below, and will be following up with some edits inspired by your critique shortly.

1. Enumerated or substantive rights: Can you clarify the distinction in your view? AFAIK American constitutional rights are substantive rights. But these ought to be substantive; do you have a suggestion to make this clearer?
2. Religious beliefs: The text provides that *persons* are to be treated with dignity and respect under the law regardless of religious *beliefs*. Actions on those beliefs are not protected, so killing on religious grounds is in no way acceptable. I see no reason why the law should not treat a person with contempt for short people with dignity or respect either. I'd be open to suggestions on how to make this passage clearer if they are not.
3. Self-ownership vs incarceration: No it should not. This should be covered by the clause granting the right to seek damages, but perhaps an explicit clause should be added, "persons forfeit these rights when ..." or similar, thoughts?
4. Jurisdictional borders: No, and I don't see how a right for persons to move precludes this, can you clarify?
5. Who enforces?: As a pluralist system, there is no prescribed answer. It is likely that Cities will have an enforcement arm, though this need not be unique. The only requirement is that the League and City governments respect and conform to this right.
6. Torts: Yes I think so. I'm open to hearing an argument why this should not be the case.
7. Sanctions: The statement is "excessively surpass". I am open to better ways to word this, I believe it is obvious the rationale why some clause to this end is warranted.
8. Exit tax: This only protects existing ("outstanding") obligations, which would be contracted willfully prior to secession; it does not create an obligation. Let me know if you think this could be clearer.
9. Popular sovereignty: Hmm, you may have a point. My intent was to say that each person individually consents but this is admittedly unclear. I will try to reword.
10. Penalize non-voting: I'm not sure I agree, how would equal *opportunity* support the idea of penalizing someone who chooses not to make use of that opportunity?
11. MoA veto: Auditing is not the same thing as overruling. A case must still be tried for wrongdoing.
12. Compulsory jury duty: "Compulsory" for citizens, which is a choice. You can think of it as citizenship being "dividend+vote in exchange for jury duty". Maybe it makes sense to limit the wording such that it's "may withhold ... for citizens opting out of jury duty" or something like that. Also it could be made clear that the terms for jury service must be established when accepting citizens.
13. "Material" defense: What does the distinction mean to you? TBH I'm not sure why I chose the word material, but to me it means "substantive".
14. Legislative standards: If cities do not conform, they would not be allowed in the League.
15. Disturbing the peace: "Disturbance of the peace" is a broad term, I'm not sure how you mean it; the objective is to allow cities to fill in the gaps with things that create real damages to its citizens like noise complaints but for which trying a case with a jury would be excessive. I certainly don't want it to become an abused clause and am open to suggestions to limit its scope further.
16. Natural authority: I'll remove "shall", as this is just an acknowledgment of natural authority
17. Ground rent: Yes, ground rent is to be collected without compensation and it is the sole source of revenue for cities. It is to be distributed to citizens less the amount allocated for the commons and public services. This I believe this to be quite clear from the 3 sections on rent, spending, and citizen's dividend. Let me know if you find something unclear about this.
18. "Does “willing to pay its rent” allow rent charges as high as the “exclusive” users care to charge?" I don't understand this question, ground rent is ground rent. True, the matter of assessing ground rent is not trivial, but it is well-defined. Meaning there are different valid methods for charging it, but there is a conceptual ideal, which the methods may be judged against.
19. CD vs public spending: Correct, as written it is up to the Citizen's how much to spend of public services. I have gone back and forth on this a lot in my own mind. On the one hand, I would like the dividend to be maximal in a sense. On the other, I would like to leave it open for experimentation. I believe that a CD incentivizes people to vote against public spending which isn't truly vital and pays for itself in ground rent increases; but it is unclear if that would be a sufficient check on special interest spending and other undesirable public expenses. This is an issue that I believe deserves much more attention, I will open a separate issue to discuss.
20. Appropriate rent: This can be worded better. The appropriate rent is exactly what would be charged to any one else. The point is that the City does need to compete with others to make use of the land. Will reword.
21. Establishment of money: Correct; the problem with central bank fiat is (a) how newly created money is distributed (implicit special interest spending), and (b) legal tender laws. Both are addressed here. I see no reason why Cities may not experiment with any form of currency which needs to compete with all other private currencies.
22. Harboring fugitives: Yes, though note that it only prohibits "inhibiting efforts", it does not create any active obligation.
23. League/City vs Federal/State: They are similar but they are not the same; IMO making the connection would create baggage I wish not to drag in.
24. Delegation and forums: Citizen's may not wish to be super involved in every vote or decision, and the forum(s) would be a place for focused discussion that would be too unruly in an entirely open public forum. In other words it's a way to create a body of representatives without grouping people's votes arbitrarily.
25. Election of City representatives: Yes, and that is intentional. I actually originally wanted this to be appointed by the mayor or governor of the City (like an ambassador), but then didn't want to be too prescriptive about it.
26. Plurality votes: Clearly I need to fix the parentheses because they should be ~38%, ~62%, & ~76%. Using an irrational number (in this case the golden ratio) assures there can be no ties, and the golden ratio in particular has a natural balance. I'll call out the golden ration directly.
27. Directives, ministries, & councils: What would you like spelled out? There is a section "Directives" which defines them, sections for each ministry which defines them, and sections for both councils which defines them in an article dedicated to them.
28. President: "Unarmed" means unarmed, they may be bureaucrats, medical staff, anything necessary for the execution of the specified responsibilities. I have clarified that this is subject to resources allocated by the councils.
29. President term limits: This is definitely worth discussing further. Term limits have always seemed quite arbitrary, but they may be valuable still. I'll open an issue.
30. Naturalization: We can't pretend we'll get rid of national borders. The Citizens of the League will need passports to travel abroad.
31. Rent collected by the League: This is only a (fixed) portion of the amount collected by cities, and determined by the citizens themselves by supermajority. Within that amount, yes there are no limits to spending. I'd suppose that for the most part there would be little League-wide CD, since people would rather get it in their city CD, but there could be value in pooling the CD too. But basically this is pre-allocated for public purposes at the League level.
32. MoA veto: See above. It has no special veto power, only the power to audit and make information public.

**Comment by luisrayas3** [comment]
Thanks again for the critique. I've addressed some of the more minor issues here: https://github.com/luisrayas3/golden-liberty/pull/4, and opened issues for a few issues I'm less sure about (#2 & #3). Closing this issue for now.
